spring:
  datasource:
    # 数据源类型 HikariCP(高性能)
    type: com.zaxxer.hikari.HikariDataSource
    # MySQL 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库配置
    url: jdbc:mysql://arch.icomponent.club:3306/arch?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: arch
    password: arch
    hikari:
      # 等待连接池分配连接的最大时长(ms) 超时 SQLException
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长(ms) 超时则被释放
      idle-timeout: 600000
      # 连接池名称
      pool-name: DataSourceHikariCP
      # 连接池的生命时长(ms) 超时而且没被使用则释放
      max-lifetime: 1800000
mybatis:
  # pojo 类所在包路径
  type-aliases-package: com.imooc.pojo
  # mapper 映射文件
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.imooc.mapper.core.CoreMapper
  not-empty: false
  identity: MYSQL
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB